/** Path of the generated hook, relative to the repository root. */
export const HOOK_PATH = '.git/hooks/pre-commit'

/**
 * The pre-commit hook. There is no `hogwash` binary on anyone's PATH: the
 * scanner is a bun script inside the skill directory, so the hook names that
 * script by absolute path.
 */
export function preCommitScript(scriptPath: string): string {
  return `#!/bin/sh
# Generated by \`hogwash hook\`. Blocks a commit whose staged prose is over the
# density threshold. Delete this file to remove the check.
set -e
files=$(git diff --cached --name-only --diff-filter=ACM -- '*.md' '*.markdown' '*.txt')
if [ -z "$files" ]; then
  exit 0
fi
# shellcheck disable=SC2086
exec bun "${scriptPath}" scan $files
`
}
