/** Path of the generated hook, relative to the repository root. */
export const HOOK_PATH = '.git/hooks/pre-commit'

const SCRIPT = `#!/bin/sh
# Generated by \`hogwash hook\`. Blocks a commit whose staged prose is over the
# density threshold. Delete this file to remove the check.
set -e
files=$(git diff --cached --name-only --diff-filter=ACM -- '*.md' '*.markdown' '*.txt')
if [ -z "$files" ]; then
  exit 0
fi
# shellcheck disable=SC2086
exec hogwash scan $files
`

export function preCommitScript(): string {
  return SCRIPT
}
