import { describe, expect, it } from 'bun:test'
import { HOOK_PATH, preCommitScript } from '../../../skills/hogwash/scripts/hook/script.js'

const EXPECTED = [
  '#!/bin/sh',
  '# Generated by `hogwash hook`. Blocks a commit whose staged prose is over the',
  '# density threshold. Delete this file to remove the check.',
  'set -e',
  "files=$(git diff --cached --name-only --diff-filter=ACM -- '*.md' '*.markdown' '*.txt')",
  'if [ -z "$files" ]; then',
  '  exit 0',
  'fi',
  '# shellcheck disable=SC2086',
  'exec hogwash scan $files',
]

describe('preCommitScript', () => {
  it('returns the generated script verbatim', () => {
    expect(preCommitScript()).toBe(`${EXPECTED.join('\n')}\n`)
  })

  it('names the hook path git looks for', () => {
    expect(HOOK_PATH).toBe('.git/hooks/pre-commit')
  })
})
